const TeaConstants = {
  RECEIVE_TEAS: 'RECEIVE_TEAS',

  RECEIVE_TEA: 'RECEIVE_TEA',

  ALL_TYPES: ['Black',
              'Red',
              'White',
              'Dark',
              'Yellow',
              'Green',
              'Oolong',
              'Herbal',
              'Other'],

  ALL_REGIONS: ['Albania',
                'Argentina',
                'Australia',
                'Bangladesh',
                'Bolivia',
                'Brazil',
                'Burkina Faso',
                'Burma',
                'Chile',
                'China',
                'Colombia',
                'Ecuador',
                'Egypt' ,
                'France',
                'Germany',
                'Guatemala',
                'India',
                'Indonesia',
                'Italy',
                'Japan',
                'Kenya',
                'Malawi',
                'Malaysia',
                'Mexico',
                'Morocco',
                'Nepal',
                'New Zealand',
                'Nigeria',
                'Paraguay',
                'Portugal',
                'Rwanda',
                'South Africa',
                'South Korea',
                'Sri Lanka',
                'Sudan',
                'Taiwan',
                'Tanzania',
                'Thailand',
                'Turkey',
                'Uganda',
                'United States of America',
                'Vietnam',
                'Zimbabwe',
                'Unknown']

};

module.exports = TeaConstants;
